### ISSUE TITLE
`!hookshot github repo url` prints stack trace but otherwise appears to work

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-hookshot#137]
```
WARN 23:02:29:121 [Bridge] Setup connection failed to handle: TypeError: Cannot read properties of undefined (reading 'reaction')
    at SetupConnection.onMessageEvent (/bin/matrix-hookshot/Connections/CommandConnection.js:58:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bridge.onRoomMessage (/bin/matrix-hookshot/Bridge.js:463:21)
```

Presuming this line:
https://github.com/Half-Shot/matrix-hookshot/blob/05852d9de89779071d63ea3a34f066b9474fada6/src/Connections/CommandConnection.ts#L51

**Comment by Half-Shot** [comment]
Should have been solved as part of #141
